kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc-ctd
  labels:
    app: blockchainctd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ibmc-file-bronze-ctd"
