---
apiVersion: batch/v1
kind: Job
metadata:
  name: createchannelctd
spec:
  backoffLimit: 1
  template:
    metadata:
      name: createchannelctd
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc-ctd
      containers:
      - name: createchanneltxctd
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "cd /shared && pwd && ls && export FABRIC_CFG_PATH=$PWD && configtxgen -profile ctdOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME} && touch /shared/status_channeltx_complete "]
        env:
        - name: CHANNEL_NAME
          value: ctd
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume


      - name: createchannelctd
        image: hyperledger/fabric-peer:1.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "while [ ! -f /shared/status_channeltx_complete ]; do echo Waiting for channeltx; sleep 2; done; peer channel create -o ${ORDERER_URL} --tls --cafile /shared/crypto-config/ordererOrganizations/example.com/orderers/ordererctd1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem -c ${CHANNEL_NAME} -f /shared/${CHANNEL_NAME}.tx && rm /shared/status_channeltx_complete && touch /shared/status_channelcreate_complete"]
        env:
        - name: CHANNEL_NAME
          value: ctd
        - name: ORDERER_URL
          value: ordererctd1:31060
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_NETWORKID
          value: cc
        - name: CORE_PEER_LOCALMSPID
          value: orgCtdMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/orgCtd.example.com/peers/cc-ctd-peer0.orgCtd.example.com/msp/
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume

