---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv-ctd
  labels:
    type: local
    name: sharedvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/shared/ctd"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc-ctd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: sharedvolume
