---
apiVersion: batch/v1
kind: Job
metadata:
  name: utils-ctd
spec:
  backoffLimit: 1
  template:
    metadata:
      name: utils-ctd
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolumectd
        persistentVolumeClaim:
          claimName: shared-pvc-ctd
      - name: dockersocket-ctd
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: cryptogenctd
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'Cryptogen Starts'; ls -l /shared/artifacts; while [ ! -d /shared/artifacts ]; do echo Waiting for configFiles; sleep 1; done; cryptogen generate --config /shared/artifacts/crypto-config.yaml && cp -r crypto-config /shared/ && for file in $(find /shared/ -iname *_sk); do echo $file; dir=$(dirname $file); echo ${dir} ;cp ${dir}/*_sk ${dir}/key.pem; done && find /shared -type d | xargs chmod a+rx && find /shared -type f | xargs chmod a+r && touch /shared/status_cryptogen_complete;"]
        volumeMounts:
        - mountPath: /shared
          name: sharedvolumectd
      - name: configtxgenctd
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'Configtxgen Starts'; ls -l /shared; sleep 1 && while [ ! -f /shared/status_cryptogen_complete ]; do echo Waiting for cryptogen; sleep 1; done; cp /shared/artifacts/configtx.yaml /shared/; cd /shared/; export FABRIC_CFG_PATH=$PWD; configtxgen -profile OrgsOrdererCtdGenesis -outputBlock genesis.block && find /shared -type d | xargs chmod a+rx && find /shared -type f | xargs chmod a+r && touch /shared/status_configtxgen_complete && rm /shared/status_cryptogen_complete;"]
        volumeMounts:
        - mountPath: /shared
          name: sharedvolumectd
          
